DROP DATABASE IF EXISTS CollegeHero;
CREATE DATABASE CollegeHero;
USE CollegeHero;

DROP TABLE IF EXISTS student;
CREATE TABLE student
(sID INT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(255) NOT NULL,
 password VARCHAR(60) NOT NULL,
 sex BOOLEAN,
 phone VARCHAR(10)
);

DROP TABLE IF EXISTS room;
CREATE TABLE room
(rID INT PRIMARY KEY AUTO_INCREMENT,
 building VARCHAR(45)
);

DROP TABLE IF EXISTS department;
CREATE TABLE department
(dID INT PRIMARY KEY AUTO_INCREMENT,
 office INT,
 title VARCHAR(45) NOT NULL,
 FOREIGN KEY (office) REFERENCES room (rID)
);

DROP TABLE IF EXISTS staff;
CREATE TABLE staff
(tID INT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(255) NOT NULL,
 department INT,
 staffTypeID INT,
 phone VARCHAR(10),
 FOREIGN KEY (department) REFERENCES department (dID)
);

DROP TABLE IF EXISTS class;
CREATE TABLE class
(cID INT PRIMARY KEY AUTO_INCREMENT,
 section INT NOT NULL,
 subject VARCHAR(45) NOT NULL,
 tID INT,
 rID INT,
 FOREIGN KEY (tID) REFERENCES staff (tID),
 FOREIGN KEY (rID) REFERENCES room (rID)
);

DROP TABLE IF EXISTS fee;
CREATE TABLE fee
(sID INT,
 cID INT,
 cost INT NOT NULL,
 PRIMARY KEY (sID, cID),
 FOREIGN KEY (sID) REFERENCES student (sID),
 FOREIGN KEY (cID) REFERENCES class (cID)
);
